- name: Find resource definitions
  find:
    paths: "{{ playbook_dir }}/{{ namespace }}/resources"
    patterns: 'Deployment-*'
  register: resource

- name: Run Transforms
  replace:
    path: "{{ r.path }}"
    regexp: '^apiVersion: .*/v1beta1'
    replace: 'apiVersion: apps/v1'
  with_items: "{{ resource.files }}"
  loop_control:
    label: "{{ r.path }}"
    loop_var: r
